milkshakeMod = RegisterMod("Milkshake!", 1)

require("loi_milkshake.TSIL").Init("loi_milkshake")

milkshakeMod.enums = require("milkshake_scripts.enums")
milkshakeMod.utility = require("milkshake_scripts.utility")
milkshakeMod.bumAPI = require("milkshake_scripts.bumAPI")

local eid = require("milkshake_scripts.modcompatibility.eid")
eid:addEid()

-- Collectibles
require("milkshake_scripts.items.collectibles.passive.blackeye")
require("milkshake_scripts.items.collectibles.familiars.spiritbum")
require("milkshake_scripts.items.collectibles.active.dicedice")
require("milkshake_scripts.items.collectibles.active.emptyslot")
require("milkshake_scripts.items.collectibles.familiars.fingore")
require("milkshake_scripts.items.collectibles.passive.firecrackerrose")
require("milkshake_scripts.items.collectibles.familiars.fragilemirror")
require("milkshake_scripts.items.collectibles.passive.glassheart")
require("milkshake_scripts.items.collectibles.active.globininabucket")
require("milkshake_scripts.items.collectibles.active.goldenshovel")
require("milkshake_scripts.items.collectibles.familiars.innerreflection")
require("milkshake_scripts.items.collectibles.passive.lachancla")
require("milkshake_scripts.items.collectibles.passive.lyra")
require("milkshake_scripts.items.collectibles.passive.milkshake")
require("milkshake_scripts.items.collectibles.passive.potofgold")
require("milkshake_scripts.items.collectibles.active.prismaticDice")
require("milkshake_scripts.items.collectibles.familiars.sharpcursor")
require("milkshake_scripts.items.collectibles.active.shatteredorb")
require("milkshake_scripts.items.collectibles.passive.sicklecell")
require("milkshake_scripts.items.collectibles.active.leviticus")
require("milkshake_scripts.items.collectibles.passive.balancedbreakfast")
require("milkshake_scripts.items.collectibles.passive.heartybreakfast")
require("milkshake_scripts.items.collectibles.passive.spoiledbreakfast")

-- Trinkets
require("milkshake_scripts.items.trinkets.amethystshard")
require("milkshake_scripts.items.trinkets.rubyshard")
require("milkshake_scripts.items.trinkets.sapphireshard")
require("milkshake_scripts.items.trinkets.emeraldshard")
require("milkshake_scripts.items.trinkets.tungstencube")
require("milkshake_scripts.items.trinkets.acidpenny.lua")
require("milkshake_scripts.items.trinkets.crystalpenny.lua")

--Pick ups
require("milkshake_scripts.items.pick ups.amethystorb")
require("milkshake_scripts.items.pick ups.chaosorb")
require("milkshake_scripts.items.pick ups.emeraldorb")
require("milkshake_scripts.items.pick ups.fruitheart")
require("milkshake_scripts.items.pick ups.rubyorb")
require("milkshake_scripts.items.pick ups.sapphireOrb")
require("milkshake_scripts.items.pick ups.tatteredpage")