milkshakeMod = RegisterMod("Milkshake!", 1)

require("loi_milkshake.TSIL").Init("loi_milkshake")

require("milkshake_scripts.enums")
require("milkshake_scripts.utility")
require("milkshake_scripts.bumAPI")

local eid = require("milkshake_scripts.modcompatibility.eid")
eid:addEid()

-- Collectibles
local blackEye = require("milkshake_scripts.items.collectibles.passive.blackeye")
local bombBuddy = require("milkshake_scripts.items.collectibles.familiars.bombbuddy")
local diceDice = require("milkshake_scripts.items.collectibles.active.dicedice")
local emptySlot = require("milkshake_scripts.items.collectibles.active.emptyslot")
local fingore = require("milkshake_scripts.items.collectibles.familiars.fingore")
local firecrackerRose = require("milkshake_scripts.items.collectibles.passive.firecrackerrose")
local glassHeart = require("milkshake_scripts.items.collectibles.passive.glassheart")
local globinInABucket = require("milkshake_scripts.items.collectibles.active.globininabucket")
local goldenShovel = require("milkshake_scripts.items.collectibles.active.goldenshovel")
local laChancla = require("milkshake_scripts.items.collectibles.passive.lachancla")
local milkshake = require("milkshake_scripts.items.collectibles.passive.milkshake")
local sharpCursor = require("milkshake_scripts.items.collectibles.familiars.sharpcursor")
local prismaticDice = require("milkshake_scripts.items.collectibles.active.prismaticDice")
local shatteredOrb = require("milkshake_scripts.items.collectibles.active.shatteredorb")
local sickleCell = require("milkshake_scripts.items.collectibles.passive.sicklecell")
require("milkshake_scripts.items.collectibles.passive.lyra")
require("milkshake_scripts.items.collectibles.passive.potofgold")
require("milkshake_scripts.items.collectibles.familiars.fragilemirror")

-- Trinkets
local amethystShard = require("milkshake_scripts.items.trinkets.amethystshard")
local rubyShard = require("milkshake_scripts.items.trinkets.rubyshard")
local sapphireShard = require("milkshake_scripts.items.trinkets.sapphireshard")
local emeraldShard = require("milkshake_scripts.items.trinkets.emeraldshard")
local tungstenCube = require("milkshake_scripts.items.trinkets.tungstencube")
--Pick ups
local amethystOrb = require("milkshake_scripts.items.pick ups.amethystorb")
local chaosOrb = require("milkshake_scripts.items.pick ups.chaosorb")
local emeraldOrb = require("milkshake_scripts.items.pick ups.emeraldorb")
local fruitHeart = require("milkshake_scripts.items.pick ups.fruitheart")
local rubyOrb = require("milkshake_scripts.items.pick ups.rubyorb")
local sapphireOrb = require("milkshake_scripts.items.pick ups.sapphireOrb")
local tatteredPage = require("milkshake_scripts.items.pick ups.tatteredpage")
