 MilkshakeVol1:AddModCompatibility("FiendFolio", function ()
    --Add coins
    MilkshakeVol1.API:AddRainbowPenny(PickupVariant.PICKUP_COIN, MilkshakeVol1.enums.Coins.SHARP_PENNY, function (_, player)
        player:UseActiveItem(CollectibleType.COLLECTIBLE_DULL_RAZOR)
        --SFXManager():Play(whatsound)
    end)

    MilkshakeVol1.API:AddRainbowPenny(PickupVariant.PICKUP_COIN, MilkshakeVol1.enums.Coins.EGG_PENNY, function (_, player)
        Isaac.Spawn(EntityType.ENTITY_FAMILIAR, FiendFolio.ITEM.FAMILIAR.FRAGILE_BOBBY, 0, player.Position, Vector.Zero, player)
        --SFXManager():Play(whatsound)
    end)

    MilkshakeVol1.API:AddRainbowPenny(PickupVariant.PICKUP_COIN, MilkshakeVol1.enums.Coins.FUZZY_PENNY, function (_, player)
        Isaac.Spawn(EntityType.ENTITY_FAMILIAR, FamiliarVariant.ATTACK_SKUZZ, 0, player.Position, Vector.Zero, player)
        --SFXManager():Play(whatsound)
    end)

    --Add entities to shattered orb
    local OrbsPerFiendFolioEntities = {
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=210, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=29, variant=960, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=170, variant=90, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=234, variant=960, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=258, variant=961, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=666, variant=20, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=1160, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=1140, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=41, variant=114, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=1100, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=240, variant=450, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=25, variant=920, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=114, variant=7, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=114, variant=7, subtype=1, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=114, variant=7,2, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=130, variant=40, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=10, variant=40, subtype=1, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=114, variant=59, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=450, variant=1, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=114, variant=21, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=450, variant=29, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=114, variant=24, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=114, variant=27, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=114, variant=52, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=450, variant=30, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=450, variant=25, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=1130, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=451, variant=220, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=451, variant=220, subtype=1, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=877, variant=114, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=450, variant=18, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=750, variant=201, subtype=11, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=108, variant=118, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=156, variant=0, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=971, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=510, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=451, variant=180, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=114, variant=50, subtype=0, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=901, }, --Enlightened
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=900, }, --Inner Eye
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=521, }, --Effigy
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=420, }, --Primemind
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=870, subtype=1, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=960, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=108, variant=111, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=108, variant=112, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=450, variant=37, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=120, variant=236, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=670, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=150, variant=23, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=341, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=21, variant=961, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=34, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=340, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=450, variant=1510, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=951, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=112, variant=1, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=956, variant=666, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=160, variant=822, subtype=2, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC_ORB, type=160, variant=80, subtype=3, },
        {trinket=MilkshakeVol1.enums.Orbs.PSYCHIC, type=120, variant=232, subtype=1, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=151, variant=5, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=310, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=750, variant=110, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=280, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=281, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=240, variant=700, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=61, variant=960, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=152, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=451, variant=151, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=430, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=43, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=208, variant=963, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=114, variant=33, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=817, variant=140, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=350, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=351, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=441, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=442, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=180, variant=21, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=1080, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=114, variant=4, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=450, variant=33, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=450, variant=2, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=450, variant=42, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=1160, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=450, variant=7, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=450, variant=43, subtype=1, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=35, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=42, variant=964, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=661, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=956, variant=666, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=1170, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=170, variant=80, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=153, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=153, subtype=1, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=154, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=160, variant=154, subtype=1, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=815, variant=960, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=450, variant=14, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=451, variant=40, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=451, variant=41, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=451, variant=42, },
        {trinket=MilkshakeVol1.enums.Orbs.FIRE, type=170, variant=110, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=61, variant=5, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=160, variant=640, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=160, variant=641, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=170, variant=30, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=114, variant=65, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=451, variant=140, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=451, variant=10, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=160, variant=1120, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=450, variant=21, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=114, variant=10, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=450, variant=5, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=160, variant=1150, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=120, variant=222, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=450, variant=20, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=160, variant=420, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=450, variant=1510, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=451, variant=250, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=451, variant=141, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=617, variant=402, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=160, variant=80, subtype=68, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=160, variant=85, subtype=395, },
        {trinket=MilkshakeVol1.enums.Orbs.ELECTRIC, type=195, variant=30},
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=360, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=29, variant=962, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=361, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=1718, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=750, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=840, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=2001, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=2000, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=666, variant=110, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=451, variant=30, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=25, variant=962, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=683, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=683, subtype=1, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=90, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=160, variant=60, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=170, variant=100, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=114, variant=57, },
        {trinket=MilkshakeVol1.enums.Orbs.NATURE, type=450, variant=6, },
    }
    MilkshakeVol1.API:AddOrbsPerEnemyForShatteredOrb(OrbsPerFiendFolioEntities)
end)